name: smk-cytokine
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - r-base=4
  - r-doFuture
  - r-foreach
  - r-future
  - r-future.apply
  - r-mikropml
  - r-rmarkdown
  - r-rpart
  - r-tidyverse
  - r-ape
  - snakemake
